---
- name: Install roles
  become: yes
  become_user: root
  become_method: sudo
  hosts: 
    - all
  pre_tasks:
    - name: Gathering facts
      setup:
  roles:
    - role: devtools
      devtools_update_packages: yes
      devtools_user: "{{ lookup('env','DEVTOOLS_USER') | default('vagrant', true) }}"
      devtools_password: "{{ lookup('env','DEVTOOLS_USER_PASSWORD') | default('vagrant', true) }}"
      devtools_group: "{{ lookup('env','DEVTOOLS_USER') | default('vagrant', true) }}"
      tags: devtools
    - role: eclipse
      eclipse_distro: neon
      eclipse_package: java
      eclipse_install_dir: /opt
      tags: eclipse
    - role: intellij
      intellij_default_maven_home: "/usr/share/maven"
      intellij_version: '2017.3.5'
      intellij_edition: community
      intellij_default_jdk_home: "/usr/lib/jvm/java-8-openjdk-amd64"
      users:
        - username: "{{ intellij_username | default('vagrant') }}"
          intellij_plugins:
            - CheckStyle-IDEA
            - PythonCore
            - org.intellij.plugins.markdown
      tags: intellij
    - role: visual-studio-code
      tags: vsc
    - role: ../../devhost
      tags: devhost
    - role: openshift_client
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    HTTP_PROXY: "{{ lookup('env','HTTP_PROXY') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
    HTTPS_PROXY: "{{ lookup('env','HTTPS_PROXY') }}"
    NO_PROXY: "{{ lookup('env','NO_PROXY') }}"
    no_proxy: "{{ lookup('env','no_proxy') }}"