---
- name: Install roles
  become: yes
  become_user: root
  become_method: sudo
  hosts: 
    - all
  pre_tasks:
    - name: Gathering facts
      setup:
  roles:
    - role: devtools
      devtools_update_packages: yes
      devtools_user: vagrant
      devtools_password: vagrant
      devtools_group: vagrant
      tags: devtools
    - role: eclipse
      eclipse_distro: neon
      eclipse_package: java
      eclipse_install_dir: /opt
      tags: eclipse
    - role: intellij
      intellij_version: '2017.3'
      intellij_edition: community
      intellij_default_jdk_home: "{{ lookup('env','JAVA_HOME') }}"
      intellij_default_maven_home: "{{ lookup('env', 'M2_HOME') }}"
      tags: intellij
    - role: visual-studio-code
      tags: vsc
  environment:
    http_proxy: "{{ lookup('env','http_proxy') }}"
    HTTP_PROXY: "{{ lookup('env','HTTP_PROXY') }}"
    https_proxy: "{{ lookup('env','https_proxy') }}"
    HTTPS_PROXY: "{{ lookup('env','HTTPS_PROXY') }}"
    NO_PROXY: "{{ lookup('env','NO_PROXY') }}"
    no_proxy: "{{ lookup('env','no_proxy') }}"