---
- src: https://github.com/mtbvang/ansible-role-devtools
  name: devtools
  version: v0.1.1
- src: https://github.com/mtbvang/ansible-role-eclipse
  name: eclipse
  version: v1.8.3
- src: https://github.com/mtbvang/ansible-role-intellij
  name: intellij
  version: 3.0.0
- src: https://github.com/mtbvang/ansible-role-visual-studio-code
  name: visual-studio-code
  version: 2.13.1
- src: https://github.com/mtbvang/ansible-role-openshift_client
  name: openshift_client
  version: v0.1.0